### ISSUE TITLE
Call on /register on startup

### ISSUE THREAD

**Issue by balessan** [oceanprotocol/dbs_filecoin#10]
**Is your feature request related to a problem? Please describe.**
As per the specification, this project should trigger a POST API call to the /register endpoint of the DBS. After testing using my docker-compose file, it does not do so 

**Describe the solution you'd like**
Upon start-up of the project, the first thing should be to execute the registration call for the storage service to be known and identified.
We should make sure that the call is also triggered every x minutes.

**Comment by xlassix** [comment]
Thanks for pointing out your observations, we  would make the update swiftly

**Comment by balessan** [comment]
Closing as solved by the last PR
