### ISSUE TITLE
Migrate to updated Lighthouse API

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/dbs_filecoin#33]
The lighhouse API that we are using is outdated and giving a 404 on this endpoint:

`https://api.lighthouse.storage/api/lighthouse/migration_request_ent`

This needs to be fixed.

**Comment by jamiehewitt15** [comment]
@nandit123 @ravish1729 We need the updated endpoint from you

**Comment by nandit123** [comment]
We are now looking into this issue, seems issue due to auth token

**Comment by jamiehewitt15** [comment]
@nandit123 ok thank you, let me know if you have any updates
