### ISSUE TITLE
Upload failing with error: `In-Adequate Token Approval or Balance`

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/dbs_filecoin#46]
Upload failing with 400 error: `Sending response with status: 400, message: In-Adequate Token Approval or Balance`

This is cause by the allowance's check: https://github.com/oceanprotocol/dbs_filecoin/blob/main/src/api/upload/upload.controller.js#L48

We need to check also DBS.js and DBS.

**Comment by jamiehewitt15** [comment]
Are you sure you have enough tokens in your wallet? I don't see anything wrong with the checks

**Comment by EnzoVezzaro** [comment]
Yes, I do have enough funds.

<img width="684" alt="Screenshot 2023-09-04 at 08 08 38" src="https://github.com/oceanprotocol/dbs_filecoin/assets/13741335/e0a072a7-287b-4851-928e-7c0a47b8e921">
<img width="345" alt="Screenshot 2023-09-04 at 08 09 01" src="https://github.com/oceanprotocol/dbs_filecoin/assets/13741335/f96959bb-2db1-4663-b85a-7b5646a6fb94">

But somehow on the logs I keep getting this: 
<img width="768" alt="Screenshot 2023-09-04 at 10 07 01" src="https://github.com/oceanprotocol/dbs_filecoin/assets/13741335/41819268-611b-4bb5-b642-5532ca12066b">

**Comment by jamiehewitt15** [comment]
The issue here is that filecoin service needs to give approval to the deposit contract rather than the dbs address. I'll fix this from dbs.js: https://github.com/oceanprotocol/dbs.js/issues/46
