### ISSUE TITLE
Going forward on the integration with DBS 

### ISSUE THREAD

**Issue by balessan** [oceanprotocol/dbs_filecoin#7]
**Describe the bug**

This is not exactly a bug, more of a report of missing information on how to integrate everything.
While using this branch of the DBS (in which I added this project as a git submodule, and added a docker-compose file listing it + the appropriate MariaDB container config), when trying to use the `getQuote/` endpoint with that JSON data input:
```json
{
          "type": "filecoin",
          "files": [
            {"length":2343545},
            {"length":2343545}
          ],
          "duration": 4353545453,
          "payment": {
              "chainId": 80001,
              "tokenAddress": "0x9aa7fEc87CA69695Dd1f879567CcF49F3ba417E2"
          },
          "userAddress": "0x6aa0ee41fa9cf65f90c06e5db8fa2834399b59b37974b21f2e405955630d472a"
}
```

I am getting this response:

```sh
{"error":{"message":"ValidationError: Invalid address. \'payment\\" must be of type object. \\"files[0]\\" must be of type object. \\"files[1]\\" must be of type object"}}' <Response [406]>
```

So a few questions:
- How to get a valid Address ? At least something I could use as demonstration/validation material. Same for the actual user wallet.
- In the json input, it looks to me that the payment and files are of type object. What am I missing ?

Thanks in advance for helping going forward on this integration :-)

**To Reproduce**
1. Go to the [DBS repo](https://github.com/oceanprotocol/decentralized_storage_backend) 
2. Clone the project
3. Checkout the [feature/docker-compose](https://github.com/oceanprotocol/decentralized_storage_backend/pull/34) branch
4. Navigate to the root of the project
5. Rename the `.env.example` file into `.env`
6. Execute `docker-compose build`
7. Execute `docker-compose up`
8. Navigate to `http://localhost:8000/docs/`
9. First trigger the `POST on /register/` example query with filecoin as default example
10. Then execute the `POST on /getQuote/` example query
11. You should get the error.

**Expected behavior**
I should get a valid response with 200 status code or 201 and a quoteID.

**Screenshots**

**Comment by xlassix** [comment]
Thanks for the feedback. The repo you referenced in your walkthrough wasn't this repo. However, from the payload you shared, the `userAddress` appears to be a private key and not a valid [Ethereum address](https://info.etherscan.com/what-is-an-ethereum-address/)

**Comment by balessan** [comment]
> Thanks for the feedback. The repo you referenced in your walkthrough wasn't this repo

Yes, it is the actual DBS, which will reference this one and mount it using the proper Dockerfile.

> However, from the payload you shared, the userAddress appears to be a private key and not a valid [Ethereum address](https://info.etherscan.com/what-is-an-ethereum-address/)

Your comment here is valid, digging into the arweave integration I know that my user address was not ok. Though the comment regarding the `payment` object structure is still valid.

**Comment by balessan** [comment]
Works now, closing.
